version: "3.7"

services:
    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=tools_hub_db
            - POSTGRES_HOST=POSTGRES_HOST
        volumes:
            - pgdata:/data/postgres
        ports:
            - "5433:5432"

    api:
        container_name: tools_hub
        build: .
        restart: always
        volumes:
            - .:/app
            - ./src:/app/src
            - ./nodemon.json:/app/nodemon.json
        depends_on:
            - db
        command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; yarn migrate && yarn dev"
        ports:
            - "3000:3000"
volumes:
    pgdata:
        driver: local
